#이전 코드 불러오기
from news_crawling import *

#joong_data = joong_crawl(header, keyword, crawl_page)
#print('[보수]중앙일보\n', joong_data)
#han_data = han_crawl(header, keyword, crawl_page)
#print('[진보]한겨레일보\n', han_data)

# 데이터 특수문자 정제 함수 정의하기
def clean_text(data):
    clean_text = re.sub('([a-zA-Z0-9_.+-]+@[a-zA-Z0-9]+\.[a-zA-Z0-9.]+)', '', data)
    clean_text = re.sub('([a-zA-Z0-9_.+-]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9.]+)', '', clean_text)
    clean_text = re.sub('(http|ftp|https)://(?:[-\w.]|(?:%[\da-fA-F{2}]))+', '', clean_text)
    clean_text = re.sub('([ㄱ-ㅎㅏ-ㅣ]+)', '', clean_text)
    clean_text = re.sub('<[^>]*>', '', clean_text)
    clean_text = re.sub('[-=+_,#/\?;:^$@*\"※~&%ㆍ!』\\‘’“”|\(\)\[\]\<\>`\'》❤♥♡☆★▲◇△▶◆■⊙▦ⓒ●◈·]', ' ', clean_text)
    clean_text = clean_text.replace("\t", " ")
    clean_text = clean_text.replace("\r", " ")
    clean_text = clean_text.replace("\n", " ")
    clean_text = clean_text.replace("  ", " ")
    return clean_text

# 데이터 정제하기
def clean_news(df):
    clean = []
    for i in df['content']:
        clean.append(clean_text(i))
    df['clean_content'] = clean

def joong_clean(df):
    # 불용어 처리
    df['title'] = df['title'].str.replace(r'\[([^)]+)\]', '')
    df['title'] = df['title'].str.replace('‘', '')
    df['title'] = df['title'].str.replace('’', '')
    df['title'] = df['title'].str.replace(',', '')
    df['title'] = df['title'].str.replace('[', '')
    df['title'] = df['title'].str.replace(']', '')
    df['title'] = df['title'].str.replace('…', '')
    df['title'] = df['title'].str.replace('-', '')
    df['title'] = df['title'].str.replace('·', '')
    df['title'] = df['title'].str.replace('“', '')
    df['title'] = df['title'].str.replace('”', '')
    df['title'] = df['title'].str.replace('"', '')
    df['title'] = df['title'].str.replace('···', '')
    df['title'] = df['title'].str.replace("'", '')
    df['title'] = df['title'].str.replace('?', '')
    df['title'] = df['title'].str.replace(':', '')
    df['title'] = df['title'].str.replace(';', '')
    df['title'] = df['title'].str.replace('→', '')
    df['content'] = df['content'].str.replace(r'\(([^)]+)\)', '')
    df['content'] = df['content'].str.replace(r'\[([^]]+)\]', '')
    df['content'] = df['content'].str.replace(r'([a-zA-Z0-9_.+-]+@[a-zA-Z0-9]+\.[a-zA-Z0-9.]+)', '')
    df['content'] = df['content'].str.replace(r'(http|ftp|https)://(?:[-\w.]|(?:%[\da-fA-F{2}]))+', '')
    df['content'] = df['content'].str.replace(r'([ㄱ-ㅎㅏ-ㅣ]+)', '')
    df['content'] = df['content'].str.replace(r'<[^>]*>', '')
    df['content'] = df['content'].str.replace(r'[-=+_,#/\?;:^$@*\"※~&%ㆍ!』\\‘’“”|\(\)\[\]\<\>`\'》❤♥♡☆★▲◇△◆■⊙▦ⓒ●·]', '')
    df['content'] = df['content'].str.replace(r'\t', ' ')
    df['content'] = df['content'].str.replace(r'\\n', '')
    df['content'] = df['content'].str.replace(r'\\r', '')
    df['content'] = df['content'].str.replace(r'\\u3000', '')
    df['content'] = df['content'].str.replace(r'\\xa0', '')
    df['content'] = df['content'].str.replace(r'\\', '')
    df['content'] = df['content'].str.replace(r'/*', '')
    df['content'] = df['content'].str.replace(r'‘', '')
    df['content'] = df['content'].str.replace(r'’', '')
    df['content'] = df['content'].str.replace(r'“', '')
    df['content'] = df['content'].str.replace(r'”', '')
    df['content'] = df['content'].str.replace(r'.', '')
    df['content'] = df['content'].str.replace(r'ufeff', '')
    df['content'] = df['content'].str.replace(r'/106061858/Donga_DT_NEWS_CV_Main', '')
    df['content'] = df['content'].str.replace(r'  ', '')
    df['content'] = df['content'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]", "")
    # 기타 불용어 처리
    df['content'] = df['content'].str.replace('[', '')
    df['content'] = df['content'].str.replace(']', '')
    df['content'] = df['content'].str.replace("'", "")
    df['content'] = df['content'].str.replace('"', '')
    df['content'] = df['content'].str.replace(',', '')
    df['content'] = df['content'].str.replace('‘', '')
    df['content'] = df['content'].str.replace('’', '')
    df['content'] = df['content'].str.replace('“', '')
    df['content'] = df['content'].str.replace('”', '')
    df['content'] = df['content'].str.replace('.', '')
    df['content'] = df['content'].str.replace('//', '')
    df['content'] = df['content'].str.replace('ㆍ', '')
    df['content'] = df['content'].str.replace('  ', '')
    df['content'] = df['content'].str.replace('·', '')
    df['content'] = df['content'].str.replace('…', '')
    df['content'] = df['content'].str.replace('〈br〉', '')
    df['content'] = df['content'].str.replace('「', '')
    df['content'] = df['content'].str.replace('」', '')
    df['content'] = df['content'].str.replace('◇', '')
    df['content'] = df['content'].str.replace('＜', '')
    df['content'] = df['content'].str.replace('＞', '')
    df['content'] = df['content'].str.replace('△', '')
    df['content'] = df['content'].str.replace('▲', '')
    df['content'] = df['content'].str.replace('=', '')
    df['content'] = df['content'].str.replace('|', '')
    df['content'] = df['content'].str.replace('||', '')
    df['content'] = df['content'].str.replace('{', '')
    df['content'] = df['content'].str.replace('}', '')
    df['content'] = df['content'].str.replace('()', '')
    df['content'] = df['content'].str.replace(';', '')
    df['content'] = df['content'].str.replace(')', '')
    df['content'] = df['content'].str.replace('(', '')
    df['content'] = df['content'].str.replace('*', '')
    df['content'] = df['content'].str.replace('＜1-2＞', '')
    df['content'] = df['content'].str.replace('©', '')
    df['content'] = df['content'].str.replace('○', ' ')
    df['content'] = df['content'].str.replace('■', '')
    df['content'] = df['content'].str.replace('●', '')
    df['content'] = df['content'].str.replace('▽', '')
    df['content'] = df['content'].str.replace('《', '')
    df['content'] = df['content'].str.replace('》', '')
    df['content'] = df['content'].str.replace('<', '')
    df['content'] = df['content'].str.replace('>', '')
    df['content'] = df['content'].str.replace('》', '')
    df['content'] = df['content'].str.replace('【', '')
    df['content'] = df['content'].str.replace('】', '')
    df['content'] = df['content'].str.replace('※', '')
    df['content'] = df['content'].str.replace('〃', '')
    df['content'] = df['content'].str.replace('사진 게티이미지', '')
    df['content'] = df['content'].str.replace('▶VOD◀', '')
    df['content'] = df['content'].str.replace('&', '')
    df['content'] = df['content'].str.replace('㈜', '')
    df['content'] = df['content'].str.replace('%', '')
    df['content'] = df['content'].str.replace('무단전재재배포', '')
    df['content'] = df['content'].str.replace('뉴시스통신사', '')
    df['content'] = df['content'].str.replace('베타뉴스', '')
    df['content'] = df['content'].str.replace('한국언론', '')
    df['content'] = df['content'].str.replace('뉴스허브', '')
    df['content'] = df['content'].str.replace('지식전문', '')
    df['content'] = df['content'].str.replace('바로가기', '')
    df['content'] = df['content'].str.replace("독자 여러분", "")
    df['content'] = df['content'].str.replace("안녕하십니까", "")
    df['content'] = df['content'].str.replace("중앙 편집국장 이정민입니다", "")
    df['content'] = df['content'].str.replace('사진', '')
    df['content'] = df['content'].str.replace('이기범', '')
    df['content'] = df['content'].str.replace('기자', '')
    df['content'] = df['content'].str.replace('뉴시스', '')
    df['content'] = df['content'].str.replace('서울뉴시스', '')
    df['content'] = df['content'].str.replace('부산뉴시스', '')
    df['content'] = df['content'].str.replace('강인식', '')
    df['content'] = df['content'].str.replace('김춘식', '')
    df['content'] = df['content'].str.replace('황보현', '')
    df['content'] = df['content'].str.replace('이재우', '')
    df['content'] = df['content'].str.replace('서유현', '')
    df['content'] = df['content'].str.replace('복거일', '')
    df['content'] = df['content'].str.replace('셜리 위추이', '')
    df['content'] = df['content'].str.replace('송길영', '')
    df['content'] = df['content'].str.replace('배명복', '')
    df['content'] = df['content'].str.replace('조현욱', '')
    df['content'] = df['content'].str.replace('이규연', '')
    # 공백제거
    df['content'] = df['content'].str.lstrip()
    df[df['content'].map(len) > 10]
    #빈 셀 없애기
    df_j = df.dropna(axis=0, how='any')
    df_j['content'].dropna()
    df_j[~df_j.content.str.contains("중앙 편집국장 이정민입니다")]
    df_j[df_j['content'].map(len) > 10]
    #중복열 삭제
    df_jdup = df_j.drop_duplicates(['content'], keep='first', inplace=False)
    df_joong = df_jdup[df_jdup['content'].map(len) > 10]
    return df_joong

def han_clean(df):
    # 불용어 처리
    df['title'] = df['title'].str.replace(r'\[([^)]+)\]', '')
    df['title'] = df['title'].str.replace('‘', '')
    df['title'] = df['title'].str.replace('’', '')
    df['title'] = df['title'].str.replace(',', '')
    df['title'] = df['title'].str.replace('[', '')
    df['title'] = df['title'].str.replace(']', '')
    df['title'] = df['title'].str.replace('…', '')
    df['title'] = df['title'].str.replace('-', '')
    df['title'] = df['title'].str.replace('·', '')
    df['title'] = df['title'].str.replace('“', '')
    df['title'] = df['title'].str.replace('”', '')
    df['title'] = df['title'].str.replace('"', '')
    df['title'] = df['title'].str.replace('···', '')
    df['title'] = df['title'].str.replace("'", '')
    df['title'] = df['title'].str.replace('?', '')
    df['title'] = df['title'].str.replace(':', '')
    df['title'] = df['title'].str.replace(';', '')
    df['title'] = df['title'].str.replace('→', '')

    df['content'] = df['content'].str.replace(r'\(([^)]+)\)', '')
    df['content'] = df['content'].str.replace(r'\[([^]]+)\]', '')
    df['content'] = df['content'].str.replace(r'([a-zA-Z0-9_.+-]+@[a-zA-Z0-9]+\.[a-zA-Z0-9.]+)', '')
    df['content'] = df['content'].str.replace(r'(http|ftp|https)://(?:[-\w.]|(?:%[\da-fA-F{2}]))+', '')
    df['content'] = df['content'].str.replace(r'([ㄱ-ㅎㅏ-ㅣ]+)', '')
    df['content'] = df['content'].str.replace(r'<[^>]*>', '')
    df['content'] = df['content'].str.replace(r'[-=+_,#/\?;:^$@*\"※~&%ㆍ!』\\‘’“”|\(\)\[\]\<\>`\'》❤♥♡☆★▲◇△◆■⊙▦ⓒ●·]', '')
    df['content'] = df['content'].str.replace(r'\t', ' ')
    df['content'] = df['content'].str.replace(r'\\n', '')
    df['content'] = df['content'].str.replace(r'\\r', '')
    df['content'] = df['content'].str.replace(r'\\u3000', '')
    df['content'] = df['content'].str.replace(r'\\xa0', '')
    df['content'] = df['content'].str.replace(r'\\', '')
    df['content'] = df['content'].str.replace(r'/*', '')
    df['content'] = df['content'].str.replace(r'‘', '')
    df['content'] = df['content'].str.replace(r'’', '')
    df['content'] = df['content'].str.replace(r'“', '')
    df['content'] = df['content'].str.replace(r'”', '')
    df['content'] = df['content'].str.replace(r'.', '')
    df['content'] = df['content'].str.replace(r'ufeff', '')
    df['content'] = df['content'].str.replace(r'/106061858/Donga_DT_NEWS_CV_Main', '')
    df['content'] = df['content'].str.replace(r'  ', '')
    df['content'] = df['content'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]", "")

    # 한글과 공백을 제외하고 모두 제거(숫자도 워드클라우드에는 필요 없기 때문에 다 제거)

    # 기타 불용어 처리
    df['content'] = df['content'].str.replace('[', '')
    df['content'] = df['content'].str.replace(']', '')
    df['content'] = df['content'].str.replace("'", "")
    df['content'] = df['content'].str.replace('"', '')
    df['content'] = df['content'].str.replace(',', '')
    df['content'] = df['content'].str.replace('‘', '')
    df['content'] = df['content'].str.replace('’', '')
    df['content'] = df['content'].str.replace('“', '')
    df['content'] = df['content'].str.replace('”', '')
    df['content'] = df['content'].str.replace('.', '')
    df['content'] = df['content'].str.replace('//', '')
    df['content'] = df['content'].str.replace('ㆍ', '')
    df['content'] = df['content'].str.replace('  ', '')
    df['content'] = df['content'].str.replace('·', '')
    df['content'] = df['content'].str.replace('…', '')
    df['content'] = df['content'].str.replace('〈br〉', '')
    df['content'] = df['content'].str.replace('「', '')
    df['content'] = df['content'].str.replace('」', '')
    df['content'] = df['content'].str.replace('◇', '')
    df['content'] = df['content'].str.replace('＜', '')
    df['content'] = df['content'].str.replace('＞', '')
    df['content'] = df['content'].str.replace('△', '')
    df['content'] = df['content'].str.replace('▲', '')
    df['content'] = df['content'].str.replace('=', '')
    df['content'] = df['content'].str.replace('|', '')
    df['content'] = df['content'].str.replace('||', '')
    df['content'] = df['content'].str.replace('{', '')
    df['content'] = df['content'].str.replace('}', '')
    df['content'] = df['content'].str.replace('()', '')
    df['content'] = df['content'].str.replace(';', '')
    df['content'] = df['content'].str.replace(')', '')
    df['content'] = df['content'].str.replace('(', '')
    df['content'] = df['content'].str.replace('*', '')
    df['content'] = df['content'].str.replace('＜1-2＞', '')
    df['content'] = df['content'].str.replace('©', '')
    df['content'] = df['content'].str.replace('○', ' ')
    df['content'] = df['content'].str.replace('■', '')
    df['content'] = df['content'].str.replace('●', '')
    df['content'] = df['content'].str.replace('▽', '')
    df['content'] = df['content'].str.replace('《', '')
    df['content'] = df['content'].str.replace('》', '')
    df['content'] = df['content'].str.replace('<', '')
    df['content'] = df['content'].str.replace('>', '')
    df['content'] = df['content'].str.replace('》', '')
    df['content'] = df['content'].str.replace('【', '')
    df['content'] = df['content'].str.replace('】', '')
    df['content'] = df['content'].str.replace('※', '')
    df['content'] = df['content'].str.replace('〃', '')
    df['content'] = df['content'].str.replace('사진 게티이미지', '')
    df['content'] = df['content'].str.replace('▶', '')
    df['content'] = df['content'].str.replace('◀', '')
    df['content'] = df['content'].str.replace('&', '')
    df['content'] = df['content'].str.replace('㈜', '')
    df['content'] = df['content'].str.replace('%', '')
    df['content'] = df['content'].str.replace('무단전재재배포', '')
    df['content'] = df['content'].str.replace('뉴시스통신사', '')
    df['content'] = df['content'].str.replace('베타뉴스', '')
    df['content'] = df['content'].str.replace('한국언론', '')
    df['content'] = df['content'].str.replace('뉴스허브', '')
    df['content'] = df['content'].str.replace('지식전문', '')
    df['content'] = df['content'].str.replace('바로가기', '')
    df['content'] = df['content'].str.replace('사진', '')
    df['content'] = df['content'].str.replace('기자', '')
    df['content'] = df['content'].str.replace('뉴시스', '')
    # 공백제거
    df['content'] = df['content'].str.lstrip()
    df[df['content'].map(len) > 10]
    df_h = df.dropna(axis=0, how='any')
    df_h['content'].dropna()
    df_h[df_h['content'].map(len) > 10]
    df_han = df_h.drop_duplicates(['content'], keep='first', inplace=False)
    return df_han


## main ##
# 정제된 기사 본문 확인
#joong_clean = joong_clean(joong_data)
#print('[정제된 중앙일보 본문]\n', joong_clean['content'])
#han_clean = han_clean( han_data)
#print('[정제된 한겨레일보 본문]\n', han_clean['content'])










